import { BASE_URL } from "./route";

export const CLIENT_ROUTE ={
    REFRESH_SESSION:`${BASE_URL.CLIENT}/refresh-session`,
    GET_TURF:`${BASE_URL.CLIENT}/getturfs`,
    GETNEARBYTURF:`${BASE_URL.CLIENT}/getnearbyturf`,
    GETSLOTS:`${BASE_URL.CLIENT}/getslots`,
    UPDATE_USER_DETAILS:`${BASE_URL.CLIENT}/update-user-details`,
    GETBOOKINGSTURF:`${BASE_URL.CLIENT}/getbookingturf`,
    GET_PAST_BOOKINGS:`${BASE_URL.CLIENT}/get-past-bookings`,
    BOOKSLOT:`${BASE_URL.CLIENT}/bookslots`,
    GET_UPCOMING_BOOKINGS:`${BASE_URL.CLIENT}/get-upcoming-bookings`,
    GETPROFILE:`${BASE_URL.CLIENT}/get-user-profile`,
    GETURFBYID:`${BASE_URL.CLIENT}/get-turfdetails`,
    GET_CHATS:`${BASE_URL.CLIENT}/get-chats`,
    ADDMONEY:`${BASE_URL.CLIENT}/add-money`,
    HOLD_SLOT:`${BASE_URL.CLIENT}/hold-slot`,
    MY_CHAT_GROUPS:`${BASE_URL.CLIENT}/my-chat-groups`,
    JOIN_HOSTED_GAME:`${BASE_URL.CLIENT}/join-hosted-game`,
    GET_TRANSACTION_HISTORY:`${BASE_URL.CLIENT}/transactionhistory`,
    GET_WALLET_BALANCE:`${BASE_URL.CLIENT}/walletbalance`,
    ADD_REVIEW:`${BASE_URL.CLIENT}/add-review`,
    HOST_GAME:`${BASE_URL.CLIENT}/host-game`,
    GET_TURF_REVIEWS:`${BASE_URL.CLIENT}/get-reviews`,
    GET_SINGLE_HOSTED_GAME:`${BASE_URL.CLIENT}/get-single-hosted-game`,
    GET_HOSTED_GAME:`${BASE_URL.CLIENT}/get-hosted-game`,
    CANCEL_BOOKING_REQUEST:`${BASE_URL.CLIENT}/cancel-request`,
    REFRESH_TOKEN:`${BASE_URL.CLIENT}/refresh-token`,
    LOGOUT:`${BASE_URL.CLIENT}/logout`,
}